tag_table = {
	replace_chars: function(x, table) {
		var res = "";
		for(i in x)
			if(x[i] in table)
				res = res + table[x[i]];
			else
				res = res + x[i];
		return res;
	},

	"\\{":                  {type:"symbol",value:"\u200B{"},
	"\\$":                  {type:"symbol",value:"\u200B$"},
	"\\\\":                 {type:"symbol",value:"\u200B\\"},
	"\\}":                  {type:"symbol",value:"\u200B}"},
	"\\_":                  {type:"symbol",value:"\u200B_"},
	"\\^":                  {type:"symbol",value:"\u200B^"},
	"\\dots":               {type:"symbol",value:"…"}, 
	"\\alpha":              {type:"symbol",value:"α"},
	"\\amalg":              {type:"symbol",value:"⨿"},
	"\\angle":              {type:"symbol",value:"∠"},
	"\\approx":             {type:"symbol",value:"≈"},
	"\\arccos":             {type:"symbol",value:"arccos"},
	"\\arccot":             {type:"symbol",value:"arccot"},
	"\\arcsin":             {type:"symbol",value:"arcsin"},
	"\\arctan":             {type:"symbol",value:"arctan"},
	"\\ast":                {type:"symbol",value:"∗"},
	"\\asymp":              {type:"symbol",value:"≍"},
	"\\backslash":          {type:"symbol",value:"⧵"},
	"\\beta":               {type:"symbol",value:"β"},
	"\\bigcirc":            {type:"symbol",value:"○"},
	"\\bigtriangledown":    {type:"symbol",value:"▽"},
	"\\bigtriangleup":      {type:"symbol",value:"△"},
	"\\blacksquare":        {type:"symbol",value:"■"},
	"\\bot":                {type:"symbol",value:"⊥"},
	"\\bowtie":             {type:"symbol",value:"⋈"},
	"\\Box":                {type:"symbol",value:"□"},
	"\\boxtimes":           {type:"symbol",value:"⊠"},
	"\\bullet":             {type:"symbol",value:"∙"},
	"\\bumpeq":             {type:"symbol",value:"≏"},
	"\\cap":                {type:"symbol",value:"∩"},
	"\\cdot":               {type:"symbol",value:"⋅"},
	"\\cdots":              {type:"symbol",value:"⋯"},
	"\\chi":                {type:"symbol",value:"χ"},
	"\\circ":               {type:"symbol",value:"∘"},
	"\\clubsuit":           {type:"symbol",value:"♣"},
	"\\complement":         {type:"symbol",value:"∁"},
	"\\cong":               {type:"symbol",value:"≅"},
	"\\copyright":          {type:"symbol",value:"©"},
	"\\cos":                {type:"symbol",value:"cos"},
	"\\cosh":               {type:"symbol",value:"cosh"},
	"\\cot":                {type:"symbol",value:"cot"},
	"\\coth":               {type:"symbol",value:"coth"},
	"\\csc":                {type:"symbol",value:"csc"},
	"\\cup":                {type:"symbol",value:"∪"},
	"\\dagger":             {type:"symbol",value:"†"},
	"\\dashv":              {type:"symbol",value:"⊣"},
	"\\ddagger":            {type:"symbol",value:"‡"},
	"\\delta":              {type:"symbol",value:"δ"},
	"\\Delta":              {type:"symbol",value:"Δ"},
	"\\diamond":            {type:"symbol",value:"⋄"},
	"\\Diamond":            {type:"symbol",value:"◇"},
	"\\diamondsuit":        {type:"symbol",value:"♢"},
	"\\div":                {type:"symbol",value:"÷"},
	"\\doteq":              {type:"symbol",value:"≐"},
	"\\downarrow":          {type:"symbol",value:"↓"},
	"\\Downarrow":          {type:"symbol",value:"⇓"},
	"\\ell":                {type:"symbol",value:"ℓ"},
	"\\emptyset":           {type:"symbol",value:"∅"},
	"\\epsilon":            {type:"symbol",value:"∊"},
	"\\equiv":              {type:"symbol",value:"≡"},
	"\\eta":                {type:"symbol",value:"η"},
	"\\eth":                {type:"symbol",value:"ð"},
	"\\exists":             {type:"symbol",value:"∃"},
	"\\flat":               {type:"symbol",value:"♭"},
	"\\forall":             {type:"symbol",value:"∀"},
	"\\frown":              {type:"symbol",value:"⌢"},
	"\\gamma":              {type:"symbol",value:"γ"},
	"\\Gamma":              {type:"symbol",value:"Γ"},
	"\\ge":                 {type:"symbol",value:"≥"},
	"\\geq":                {type:"symbol",value:"≥"},
	"\\gets":               {type:"symbol",value:"⟵"},
	"\\gg":                 {type:"symbol",value:"≫"},
	"\\gneqq":              {type:"symbol",value:"≩"},
	"\\hbar":               {type:"symbol",value:"ℏ"},
	"\\heartsuit":          {type:"symbol",value:"♡"},
	"\\hookleftarrow":      {type:"symbol",value:"↩"},
	"\\hookrightarrow":     {type:"symbol",value:"↪"},
	"\\idotsint":           {type:"symbol",value:"∫⋯∫"},
	"\\iff":                {type:"symbol",value:"⟺"},
	"\\iiint":              {type:"symbol",value:"∭"},
	"\\iint":               {type:"symbol",value:"∬"},
	"\\Im":                 {type:"symbol",value:"ℑ"},
	"\\imath":              {type:"symbol",value:"ı"},
	"\\implies":            {type:"symbol",value:"⇒"},
	"\\in":                 {type:"symbol",value:"∈"},
	"\\infty":              {type:"symbol",value:"∞"},
	"\\int":                {type:"symbol",value:"∫"},
	"\\iota":               {type:"symbol",value:"ι"},
	"\\jmath":              {type:"symbol",value:"ȷ"},
	"\\Join":               {type:"symbol",value:"⋈"},
	"\\kappa":              {type:"symbol",value:"κ"},
	"\\lambda":             {type:"symbol",value:"λ"},
	"\\Lambda":             {type:"symbol",value:"Λ"},
	"\\land":               {type:"symbol",value:"∧"},
	"\\langle":             {type:"symbol",value:"〈"},
	"\\lceil":              {type:"symbol",value:"⌈"},
	"\\le":                 {type:"symbol",value:"≤"},
	"\\leadsto":            {type:"symbol",value:"↝"},
	"\\leftarrow":          {type:"symbol",value:"←"},
	"\\Leftarrow":          {type:"symbol",value:"⇐"},
	"\\leftharpoondown":    {type:"symbol",value:"↽"},
	"\\leftharpoonup":      {type:"symbol",value:"↼"},
	"\\leftrightarrow":     {type:"symbol",value:"↔"},
	"\\Leftrightarrow":     {type:"symbol",value:"⇔"},
	"\\leq":                {type:"symbol",value:"≤"},
	"\\leqq":               {type:"symbol",value:"≦"},
	"\\lfloor":             {type:"symbol",value:"⌊"},
	"\\lhd":                {type:"symbol",value:"⊲"},
	"\\ll":                 {type:"symbol",value:"≪"},
	"\\lneqq":              {type:"symbol",value:"≨"},
	"\\lnsim":              {type:"symbol",value:"≴"},
	"\\longleftarrow":      {type:"symbol",value:"←"},
	"\\Longleftarrow":      {type:"symbol",value:"⇐"},
	"\\longleftrightarrow": {type:"symbol",value:"↔"},
	"\\Longleftrightarrow": {type:"symbol",value:"⇔"},
	"\\longmapsto":         {type:"symbol",value:"⇖"},
	"\\longrightarrow":     {type:"symbol",value:"→"},
	"\\Longrightarrow":     {type:"symbol",value:"⇒"},
	"\\lor":                {type:"symbol",value:"∨"},
	"\\mapsto":             {type:"symbol",value:"↦"},
	"\\measuredangle":      {type:"symbol",value:"∡"},
	"\\mho":                {type:"symbol",value:"℧"},
	"\\mid":                {type:"symbol",value:"∣"},
	"\\models":             {type:"symbol",value:"⊨"},
	"\\mp":                 {type:"symbol",value:"∓"},
	"\\mu":                 {type:"symbol",value:"μ"},
	"\\nabla":              {type:"symbol",value:"∇"},
	"\\natural":            {type:"symbol",value:"♮"},
	"\\nearrow":            {type:"symbol",value:"↗"},
	"\\neg":                {type:"symbol",value:"¬"},
	"\\neq":                {type:"symbol",value:"≠"},
	"\\nexists":            {type:"symbol",value:"∄"},
	"\\ngeq":               {type:"symbol",value:"≠"},
	"\\ngtr":               {type:"symbol",value:"≯"},
	"\\ni":                 {type:"symbol",value:"∋"},
	"\\nleq":               {type:"symbol",value:"≰"},
	"\\nless":              {type:"symbol",value:"≮"},
	"\\nmid":               {type:"symbol",value:"∤"},
	"\\notin":              {type:"symbol",value:"∉"},
	"\\nparallel":          {type:"symbol",value:"∦"},
	"\\nsubseteq":          {type:"symbol",value:"⊊"},
	"\\nsupseteq":          {type:"symbol",value:"⊋"},
	"\\nwarrow":            {type:"symbol",value:"↖"},
	"\\odot":               {type:"symbol",value:"⊙"},
	"\\oiiint":             {type:"symbol",value:"∰"},
	"\\oiint":              {type:"symbol",value:"∯"},
	"\\oint":               {type:"symbol",value:"∮"},
	"\\omega":              {type:"symbol",value:"ω"},
	"\\Omega":              {type:"symbol",value:"Ω"},
	"\\ominus":             {type:"symbol",value:"⊖"},
	"\\oplus":              {type:"symbol",value:"⊕"},
	"\\oslash":             {type:"symbol",value:"⊘"},
	"\\otimes":             {type:"symbol",value:"⊗"},
	"\\P":                  {type:"symbol",value:"¶"},
	"\\parallel":           {type:"symbol",value:"∥"},
	"\\partial":            {type:"symbol",value:"∂"},
	"\\perp":               {type:"symbol",value:"⊥"},
	"\\phi":                {type:"symbol",value:"φ"},
	"\\Phi":                {type:"symbol",value:"Φ"},
	"\\pm":                 {type:"symbol",value:"±"},
	"\\prec":               {type:"symbol",value:"≺"},
	"\\preceq":             {type:"symbol",value:"≼"},
	"\\prime":              {type:"symbol",value:"′"},
	"\\prod":               {type:"symbol",value:"∏"},
	"\\propto":             {type:"symbol",value:"∝"},
	"\\psi":                {type:"symbol",value:"ψ"},
	"\\Psi":                {type:"symbol",value:"Ψ"},
	"\\rangle":             {type:"symbol",value:"〉"},
	"\\rceil":              {type:"symbol",value:"⌉"},
	"\\Re":                 {type:"symbol",value:"ℜ"},
	"\\rfloor":             {type:"symbol",value:"⌋"},
	"\\rhd":                {type:"symbol",value:"⊳"},
	"\\rightarrow":         {type:"symbol",value:"→"},
	"\\Rightarrow":         {type:"symbol",value:"⇒"},
	"\\rightharpoondown":   {type:"symbol",value:"⇁"},
	"\\rightharpoonup":     {type:"symbol",value:"⇀"},
	"\\rightleftharpoons":  {type:"symbol",value:"⇌"},
	"\\S":                  {type:"symbol",value:"§"},
	"\\searrow":            {type:"symbol",value:"↘"},
	"\\sec":                {type:"symbol",value:"sec"},
	"\\setminus":           {type:"symbol",value:"∖"},
	"\\sharp":              {type:"symbol",value:"♯"},
	"\\sim":                {type:"symbol",value:"∼"},
	"\\simeq":              {type:"symbol",value:"≃"},
	"\\sin":                {type:"symbol",value:"sin"},
	"\\sinh":               {type:"symbol",value:"sinh"},
	"\\smile":              {type:"symbol",value:"⌣"},
	"\\spadesuit":          {type:"symbol",value:"♠"},
	"\\sphericalangle":     {type:"symbol",value:"∢"},
	"\\sqcap":              {type:"symbol",value:"⊓"},
	"\\sqcup":              {type:"symbol",value:"⊔"},
	"\\sqsubset":           {type:"symbol",value:"⊏"},
	"\\sqsubseteq":         {type:"symbol",value:"⊑"},
	"\\sqsupset":           {type:"symbol",value:"⊐"},
	"\\sqsupseteq":         {type:"symbol",value:"⊒"},
	"\\square":             {type:"symbol",value:"□"},
	"\\star":               {type:"symbol",value:"⋆"},
	"\\subset":             {type:"symbol",value:"⊂"},
	"\\subseteq":           {type:"symbol",value:"⊆"},
	"\\succ":               {type:"symbol",value:"≻"},
	"\\succeq":             {type:"symbol",value:"≽"},
	"\\sum":                {type:"symbol",value:"∑"},
	"\\supset":             {type:"symbol",value:"⊃"},
	"\\supseteq":           {type:"symbol",value:"⊇"},
	"\\surd":               {type:"symbol",value:"√"},
	"\\swarrow":            {type:"symbol",value:"↙"},
	"\\tan":                {type:"symbol",value:"tan"},
	"\\tanh":               {type:"symbol",value:"tanh"},
	"\\theta":              {type:"symbol",value:"θ"},
	"\\Theta":              {type:"symbol",value:"Θ"},
	"\\times":              {type:"symbol",value:"×"},
	"\\top":                {type:"symbol",value:"⊤"},
	"\\triangle":           {type:"symbol",value:"△"},
	"\\triangleleft":       {type:"symbol",value:"◁"},
	"\\triangleright":      {type:"symbol",value:"▷"},
	"\\unlhd":              {type:"symbol",value:"⊴"},
	"\\unrhd":              {type:"symbol",value:"⊵"},
	"\\uparrow":            {type:"symbol",value:"↑"},
	"\\Uparrow":            {type:"symbol",value:"⇑"},
	"\\updownarrow":        {type:"symbol",value:"↕"},
	"\\Updownarrow":        {type:"symbol",value:"⇕"},
	"\\uplus":              {type:"symbol",value:"⊎"},
	"\\upsilon":            {type:"symbol",value:"υ"},
	"\\Upsilon":            {type:"symbol",value:"Υ"},
	"\\varepsilon":         {type:"symbol",value:"ε"},
	"\\varnothing":         {type:"symbol",value:"∅"},
	"\\varphi":             {type:"symbol",value:"ϕ"},
	"\\vartheta":           {type:"symbol",value:"ϑ"},
	"\\vdash":              {type:"symbol",value:"⊢"},
	"\\vee":                {type:"symbol",value:"∨"},
	"\\wedge":              {type:"symbol",value:"∧"},
	"\\wp":                 {type:"symbol",value:"℘"},
	"\\wr":                 {type:"symbol",value:"≀"},
	"\\zeta":               {type:"symbol",value:"ζ"},
	"\\theta":              {type:"symbol",value:"θ"},
	"\\Theta":              {type:"symbol",value:"Θ"},
	"\\nu":                 {type:"symbol",value:"ν"}, 
	"\\xi":                 {type:"symbol",value:"ξ"},
	"\\Xi":                 {type:"symbol",value:"Ξ"},
	"\\pi":                 {type:"symbol",value:"π"}, 
	"\\Pi":                 {type:"symbol",value:"Π"},
	"\\rho":                {type:"symbol",value:"ρ"},
	"\\sigma":              {type:"symbol",value:"σ"},
	"\\Sigma":              {type:"symbol",value:"Σ"},
	"\\varsigma":           {type:"symbol",value:"ς"},
	"\\tau":                {type:"symbol",value:"τ"},
	"\\upsilon":            {type:"symbol",value:"υ"},
	
	"\\sqrt": {type: "decorator", value: function(x) {return "√(" + x +")"}},
	"\\bar": {type: "decorator", value: function(x) { return x.replace(/(.{1})/g,"$1\u0305"); }},
	"\\vec": {type: "decorator", value: function(x) { return x.replace(/(.{1})/g,"$1\u20D7"); }},
	"\\dot": {type: "decorator", value: function(x) { return x.replace(/(.{1})/g,"$1\u0307"); }},
	"\\not": {type: "decorator", value: function(x) {
			var table = {"=":"≠", "<":"≮", ">":"≯", "≤":"≰", "≥":"≱", "∃":"∄"};
			return tag_table.replace_chars(x, table);
		}},
	"\\mathfrak": {type: "decorator", value: function(x) {
			var table = {"A": "𝔄", "N": "𝔑", "a": "𝔞", "n": "𝔫",
						"B": "𝔅", "O": "𝔒", "b": "𝔟", "o": "𝔬",
						"C": "𝕮", "P": "𝔓", "c": "𝔠", "p": "𝔭",
						"D": "𝔇", "Q": "𝔔", "d": "𝔡", "q": "𝔮",
						"E": "𝔈", "R": "𝕽", "e": "𝔢", "r": "𝔯",
						"F": "𝔉", "S": "𝔖", "f": "𝔣", "s": "𝔰",
						"G": "𝔊", "T": "𝔗", "g": "𝔤", "t": "𝔱",
						"H": "𝕳", "U": "𝔘", "h": "𝔥", "u": "𝔲",
						"I": "𝕴", "V": "𝔙", "I": "𝔦", "v": "𝔳",
						"J": "𝔍", "W": "𝔚", "j": "𝔧", "w": "𝔴",
						"K": "𝔎", "X": "𝔛", "k": "𝔨", "x": "𝔵",
						"L": "𝔏", "Y": "𝔜", "l": "𝔩", "y": "𝔶",
						"M": "𝕸", "Z": "𝖅", "m": "𝔪", "z": "𝔷"};
			return tag_table.replace_chars(x, table);
		}},
	"\\frac": {type: "decorator2", value: function(x,y) {
			var table = {"1/4": "¼", 
						"1/2": "½", 
						"3/4": "¾", 
						"1/3": "⅓", 
						"2/3": "⅔", 
						"1/5": "⅕", 
						"2/5": "⅖", 
						"3/5": "⅗", 
						"4/5": "⅘", 
						"1/6": "⅙", 
						"5/6": "⅚", 
						"1/8": "⅛", 
						"3/8": "⅜", 
						"5/8": "⅝", 
						"7/8": "⅞"}
			if(x+"/"+y in table)
				return table[x+"/"+y];
			return "(" + x + ")/(" + y + ")";
		}},
	"\\mathcal": {type: "decorator", value: function(x) {
			var table = {"A": "𝓐", "N": "𝓝", "a": "𝓪", "n": "𝓷",
						"B": "𝓑", "O": "𝓞", "b": "𝓫", "o": "𝓸",
						"C": "𝓒", "P": "𝓟", "c": "𝓬", "p": "𝓹",
						"D": "𝓓", "Q": "𝓠", "d": "𝓭", "q": "𝓺",
						"E": "𝓔", "R": "𝓡", "e": "𝓮", "r": "𝓻",
						"F": "𝓕", "S": "𝓢", "f": "𝓯", "s": "𝓼",
						"G": "𝓖", "T": "𝓣", "g": "𝓰", "t": "𝓽",
						"H": "𝓗", "U": "𝓤", "h": "𝓱", "u": "𝓾",
						"I": "𝓘", "V": "𝓥", "I": "𝓲", "v": "𝓿",
						"J": "𝓙", "W": "𝓦", "j": "𝓳", "w": "𝔀",
						"K": "𝓚", "X": "𝓧", "k": "𝓴", "x": "𝔁",
						"L": "𝓛", "Y": "𝓨", "l": "𝓵", "y": "𝔂",
						"M": "𝓜", "Z": "𝓩", "m": "𝓶", "z": "𝔃"};
			return tag_table.replace_chars(x, table);
		}},
	"\\mathbb": {type: "decorator", value: function(x) {
			var table = {"A": "𝔸", "N": "ℕ", "a": "𝕒", "n": "𝕟",
						"B": "𝔹", "O": "𝕆", "b": "𝕓", "o": "𝕠",
						"C": "ℂ", "P": "ℙ", "c": "𝕔", "p": "𝕡",
						"D": "𝔻", "Q": "ℚ", "d": "𝕕", "q": "𝕢",
						"E": "𝔼", "R": "ℝ", "e": "𝕖", "r": "𝕣",
						"F": "𝔽", "S": "𝕊", "f": "𝕗", "s": "𝕤",
						"G": "𝔾", "T": "𝕋", "g": "𝕘", "t": "𝕥",
						"H": "ℍ", "U": "𝕌", "h": "𝕙", "u": "𝕦",
						"I": "𝕀", "V": "𝕍", "I": "𝕚", "v": "𝕧",
						"J": "𝕁", "W": "𝕎", "j": "𝕛", "w": "𝕨",
						"K": "𝕂", "X": "𝕏", "k": "𝕜", "x": "𝕩",
						"L": "𝕃", "Y": "𝕐", "l": "𝕝", "y": "𝕪",
						"M": "𝕄", "Z": "ℤ", "m": "𝕞", "z": "𝕫",
						"0": "𝟘", "3": "𝟛", "6": "𝟞", "9": "𝟡",
						"1": "𝟙", "4": "𝟜", "7": "𝟟",
						"2": "𝟚", "5": "𝟝", "8": "𝟠"};
			return tag_table.replace_chars(x, table);
		}},
	"\\textbf": {type: "decorator", 
			value: function(x){ 
				var table = {"a": "𝐚", "h": "𝐡", "o": "𝐨", "v": "𝐯",
						"b": "𝐛", "i": "𝐢", "p": "𝐩", "w": "𝐰",
						"c": "𝐜", "j": "𝐣", "q": "𝐪", "x": "𝐱",
						"d": "𝐝", "k": "𝐤", "r": "𝐫", "y": "𝐲",
						"e": "𝐞", "l": "𝐥", "s": "𝐬", "z": "𝐳",
						"f": "𝐟", "m": "𝐦", "t": "𝐭",
						"g": "𝐠", "n": "𝐧", "u": "𝐮",
						"A": "𝐀", "H": "𝐇", "O": "𝐎", "V": "𝐕",
						"B": "𝐁", "I": "𝐈", "P": "𝐏", "W": "𝐖",
						"C": "𝐂", "J": "𝐉", "Q": "𝐐", "X": "𝐗",
						"D": "𝐃", "K": "𝐊", "R": "𝐑", "Y": "𝐘",
						"E": "𝐄", "L": "𝐋", "S": "𝐒", "Z": "𝐙",
						"F": "𝐅", "M": "𝐌", "T": "𝐓",
						"G": "𝐆", "N": "𝐍", "U": "𝐔"};
				return tag_table.replace_chars(x, table);
			}
		},
	"\\textit": {type: "decorator", 
			value: function(x){ 
				var table = {"A": "𝘈", "N": "𝘕", "a": "𝘢", "n": "𝘯",
							"B": "𝘉", "O": "𝘖", "b": "𝘣", "o": "𝘰",
							"C": "𝘊", "P": "𝘗", "c": "𝘤", "p": "𝘱",
							"D": "𝘋", "Q": "𝘘", "d": "𝘥", "q": "𝘲",
							"E": "𝘌", "R": "𝘙", "e": "𝘦", "r": "𝘳",
							"F": "𝘍", "S": "𝘚", "f": "𝘧", "s": "𝘴",
							"G": "𝘎", "T": "𝘛", "g": "𝘨", "t": "𝘵",
							"H": "𝘏", "U": "𝘜", "h": "𝘩", "u": "𝘶",
							"I": "𝘐", "V": "𝘝", "I": "𝘪", "v": "𝘷",
							"J": "𝘑", "W": "𝘞", "j": "𝘫", "w": "𝘸",
							"K": "𝘒", "X": "𝘟", "k": "𝘬", "x": "𝘹",
							"L": "𝘓", "Y": "𝘠", "l": "𝘭", "y": "𝘺",
							"M": "𝘔", "Z": "𝘡", "m": "𝘮", "z": "𝘻"
							};
				return tag_table.replace_chars(x, table);
			}
		},
	"^": {type: "decorator",
		value: function(x) {
			var table = {"0":"⁰", "1":"¹", "2":"²", "3":"³", "4":"⁴", "5":"⁵", 
						"6":"⁶", "7":"⁷", "8":"⁸", "9":"⁹", "+":"⁺", "-":"⁻", 
						"=":"⁼", "(":"⁽", ")":"⁾", "a":"ᵃ", "b":"ᵇ", "c":"ᶜ", 
						"d":"ᵈ", "e":"ᵉ", "f":"ᶠ", "g":"ᵍ", "h":"ʰ", "i":"ⁱ", 
						"j":"ʲ", "k":"ᵏ", "l":"ˡ", "m":"ᵐ", "n":"ⁿ", "o":"ᵒ", 
						"p":"ᵖ", "r":"ʳ", "s":"ˢ", "t":"ᵗ", "u":"ᵘ", "v":"ᵛ", 
						"w":"ʷ", "x":"ˣ", "y":"ʸ", "z":"ᶻ", "A":"ᴬ", "B":"ᴮ", 
						"D":"ᴰ", "E":"ᴱ", "G":"ᴳ", "H":"ᴴ", "I":"ᴵ", "J":"ᴶ", 
						"K":"ᴷ", "L":"ᴸ", "M":"ᴹ", "N":"ᴺ", "O":"ᴼ", "P":"ᴾ", 
						"R":"ᴿ", "T":"ᵀ", "U":"ᵁ", "V":"ⱽ", "W":"ᵂ", "α":"ᵅ", 
						"β":"ᵝ", "γ":"ᵞ", "δ":"ᵟ", "ε":"ᵋ", "θ":"ᶿ", "ι":"ᶥ", 
						"ϕ":"ᶲ", "φ":"ᵠ", "χ":"ᵡ"};
	
			return tag_table.replace_chars(x, table);
		}},
	"_": {type: "decorator",
		value: function(x) {
			var table = {"0":"₀", "1":"₁", "2":"₂", "3":"₃", "4":"₄", "5":"₅", 
						"6":"₆", "7":"₇", "8":"₈", "9":"₉", "+":"₊", "-":"₋", 
						"=":"₌", "(":"₍", ")":"₎", "a":"ₐ", "e":"ₑ", "h":"ₕ", 
						"i":"ᵢ", "j":"ⱼ", "k":"ₖ", "l":"ₗ", "m":"ₘ", "n":"ₙ", 
						"o":"ₒ", "p":"ₚ", "r":"ᵣ", "s":"ₛ", "t":"ₜ", "u":"ᵤ", 
						"v":"ᵥ", "x":"ₓ", "β":"ᵦ", "γ":"ᵧ", "ρ":"ᵨ", "φ":"ᵩ", 
						"A":"ᴀ", "B":"ʙ", "C":"c", "D":"ᴅ", "E":"ᴇ", "F":"ꜰ", 
						"G":"ɢ", "H":"ʜ", "I":"ı", "J":"ᴊ ", "K":"ᴋ", "L":"ʟ", 
						"M":"ᴍ", "N":"ɴ", "O":"o", "P":"ᴘ", "R":"ʀ", "S":"ꜱ", 
						"T":"ᴛ", "U":"ᴜ", "V":"v", "W":"w", "X":"x", "Y":"ʏ",
						"Z":"z", "χ":"ᵪ"};
			console.log("subdecorator: " + x);
			return tag_table.replace_chars(x, table);
		}}
};
